title: Andrea Wynn
logo: "/images/profile pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computer Science & Software Engineering & Math @ Rose-Hulman Institute of Technology 
  <br><br>
  
  Hello! My name is Andrea. I will be working as an SDE intern at Amazon for the summer of 2021, and am seeking another software engineering internship or full-time position starting summer 2022. I'd love to get in touch with you! 
  
  <br><br>
  <a href="https://www.linkedin.com/in/andrea-wynn/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://github.com/andrea-00">View My GitHub Profile</a>
  <br>
  <a href="https://devpost.com/wynna?ref_content=user-portfolio&ref_feature=portfolio&ref_medium=global-nav">View My DevPost Profile</a> 
  <br>
  <a href="https://www.hackerrank.com/wynna?hr_r=1">View My HackerRank Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
