title: Andrea Wynn
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  CS/SE/MA Triple Major @ Rose-Hulman Institute of Technology 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/andrea-wynn/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://www.hackerrank.com/wynna?hr_r=1">View My HackerRank Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
